name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prerequisites
      run: |
        gem install xcpretty
    - name: Build
      run: |
        set -o pipefail
        xcodebuild -project MensaDresden.xcodeproj -scheme MensaDresden -destination 'platform=iOS Simulator,name=iPhone 12' build | xcpretty --color
    - name: Test
      run: |
        set -o pipefail
        xcodebuild -project MensaDresden.xcodeproj -scheme MensaDresden -destination 'platform=iOS Simulator,name=iPhone 12' test | xcpretty --color --test
